name: Fan

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Lint Step
        run: echo "Lint start" && sleep 5 && echo "Lint end"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Build start" && sleep 10 && echo "Build end"

  report:
    needs: [lint, build]
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Report here"
