name: Fan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Build start" & sleep 10 & echo "Build end"

  report:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Report here"
