name: Release

on:
  release:
    types:
      - created

jobs:
  release-a:
    if: contains(github.ref, 'refs/tags/tag-a-')
    
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  release-b:
    if: contains(github.ref, 'refs/tags/tag-b-')
    
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

